//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypture
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cipher
    {
        public long ItemId { get; set; }
        public byte[] CipherText { get; set; }
        public byte[] CipherVector { get; set; }
        public long CipherParams { get; set; }
        public long? ContentSuite { get; set; }
        public byte[] AuthenticationTag { get; set; }
        public string ProtectionDescriptor { get; set; }
        public byte[] ProtectedKey { get; set; }
        public byte[] Signature { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
