<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <OutputType>Exe</OutputType>
    <AssemblyName>Crypture.Tests</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <AppConfig>..\Code\App.config</AppConfig>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Bcl.Cryptography">
      <HintPath>..\Code\packages\Microsoft.Bcl.Cryptography.10.0.12\lib\net462\Microsoft.Bcl.Cryptography.dll</HintPath>
    </Reference>
    <Reference Include="System.Formats.Asn1">
      <HintPath>..\Code\packages\System.Formats.Asn1.10.0.12\lib\net462\System.Formats.Asn1.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>..\Code\packages\System.Memory.4.6.3\lib\net462\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>..\Code\packages\System.Runtime.CompilerServices.Unsafe.6.1.2\lib\net462\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="System.Buffers">
      <HintPath>..\Code\packages\System.Buffers.4.6.1\lib\net462\System.Buffers.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics.Vectors">
      <HintPath>..\Code\packages\System.Numerics.Vectors.4.6.1\lib\net462\System.Numerics.Vectors.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Numerics" />
    <Reference Include="System.Data" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Security" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="ControlzEx">
      <HintPath>..\Code\packages\ControlzEx.3.0.2.4\lib\net462\ControlzEx.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Interactivity">
      <HintPath>..\Code\packages\ControlzEx.3.0.2.4\lib\net462\System.Windows.Interactivity.dll</HintPath>
    </Reference>
    <Reference Include="Fluent">
      <HintPath>..\Code\packages\Fluent.Ribbon.6.1.0.326\lib\net462\Fluent.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework">
      <HintPath>..\Code\packages\EntityFramework.6.2.0\lib\net45\EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.SQLite">
      <HintPath>..\Code\packages\System.Data.SQLite.Core.1.0.109.2\lib\net46\System.Data.SQLite.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.SQLite.EF6">
      <HintPath>..\Code\packages\System.Data.SQLite.EF6.1.0.109.0\lib\net46\System.Data.SQLite.EF6.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.SQLite.Linq">
      <HintPath>..\Code\packages\System.Data.SQLite.Linq.1.0.109.0\lib\net46\System.Data.SQLite.Linq.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\Code\Crypture.csproj">
      <Project>{E83DCF80-C45B-4F17-9F96-309CAE6168F5}</Project>
      <Name>Crypture</Name>
    </ProjectReference>
    <Compile Include="RegressionTests.cs" />
    <Compile Include="CertificateEncryptionTests.cs" />
    <Compile Include="HealthCheckTests.cs" />
    <None Include="..\Code\Data\SQLite.sql">
      <Link>SQLite.sql</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="..\Code\packages\System.Data.SQLite.Core.1.0.109.2\build\net46\System.Data.SQLite.Core.targets" />
</Project>
