<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>14.0</LangVersion>
    <Nullable>disable</Nullable>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <AppConfig>..\Code\App.config</AppConfig>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Code\Crypture.csproj" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.6" />
    <None Include="..\Code\App.config" Link="Crypture.exe.config" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Code\Data\SQLite.sql" Link="SQLite.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
